### PR TITLE
Reduce dependencies

### PR DESCRIPTION
**Pull request by dieghernan**
Some dependencies moved to pkgdown action.

Also, restart the cache to perform a full clean test

#230

### CODE REVIEW

**Comment by dieghernan** [comment]
Now `add_nuts_level` uses `regions::validate_nuts_regions` and is compatible with released version of the function

**Comment by dieghernan** [comment]
This is ready with small changes on deprecated functions and the vignette,

**Comment by antagomir** [comment]
Seems good to me at least.

**Review by antagomir — APPROVED** [review]

**Comment by dieghernan** [comment]
In the fresh installation (macOS) of the action I see now:

✔ 92 + 3 pkgs | kept 94, updated 1, new 0 | downloaded 1 (NA B) [23.5s]

vs the previous one:

✔ 143 + 3 pkgs | kept 145, updated 1, new 0 | downloaded 1 (NA B) [33.3s]

**Review by pitkant — APPROVED** [review]
Great job, thanks!

**Pull request merged**
