### PR TITLE
Set eurostat_url as an option when package starts

### PR DESCRIPTION
**Pull request by paulrougieux**
As discussed in #123 

Set the option only if it is not already set, inspired by dplyr:
https://github.com/tidyverse/dplyr/blob/bbcfe99e29fe737d456b0d7adc33d3c445a32d9d/R/zzz.r

### CODE REVIEW

**Comment by antagomir** [comment]
Some travis checks not successfull. I did not find the explanation yet. https://travis-ci.org/rOpenGov/eurostat/jobs/421445589

**Comment by paulrougieux** [comment]
Related issues could be random error happening with apt get calls:
https://github.com/travis-ci/travis-ci/issues/8507
and 
https://github.com/travis-ci/travis-ci/issues/9112
Can you relaunch the travis build?

**Comment by paulrougieux** [comment]
This travis job ran successfully https://travis-ci.org/rOpenGov/eurostat/jobs/421445590
And this one failed https://travis-ci.org/rOpenGov/eurostat/jobs/421445589
The funny thing is that they are both based on the same commit: Commit 7ade7ae

**Comment by antagomir** [comment]
Yes I had noticed those points too.. but relaunching the build magically solved the issue. Merging.

**Comment by antagomir** [comment]
.. and many thanks!

**Comment by paulrougieux** [comment]
OK
> Next time perhaps desirable to make the pull request to the devel branch.

Sorry, I didn't know about the devel branch.

I temporarily patched the code for a colleague who uses the package to collect data.
Can you please notify us here when the [eurostat package](https://cran.r-project.org/web/packages/eurostat/index.html) is updated on CRAN?

**Pull request merged**
