### PR TITLE
Fix RCMD action

### PR DESCRIPTION
**Pull request by dieghernan**

### CODE REVIEW

**Comment by dieghernan** [comment]
Hi @antagomir @pitkant 

I noticed that the R CMD Check was falling recently. This PR updates the action config file so now it works again, avoiding the errors on the action setup

Regards

**Review by pitkant — APPROVED** [review]
Looks good

**Comment by antagomir** [comment]
Is this something we should consider also for other rOpenGov packages?

**Comment by dieghernan** [comment]
`v2` version of the workflows provide better performance, BUT current versions should be working as well.

My opinion is that the action may be upgraded in case there is an issue with the workflow itself (i.e. dependencies not being installed) on a case-by-case basis. Otherwise there is not need to upgrade them in the short term.

**Comment by pitkant** [comment]
> `v2` version of the workflows provide better performance, BUT current versions should be working as well.
> 
> My opinion is that the action may be upgraded in case there is an issue with the workflow itself (i.e. dependencies not being installed) on a case-by-case basis. Otherwise there is not need to upgrade them in the short term.

I agree that if things are working, there is no need to tinker. Of course r-lib's GitHub Actions get updated from time to time and old actions can have surprising issues if they are not updated regularly. One example (and this is more of a note to self) is that actions may stop working if they have Ubuntu 18.04 as platform, as mentioned in this tweet by Gábor Csárdi: https://twitter.com/GaborCsardi/status/1561694747235958790

**Comment by antagomir** [comment]
Great!

**Pull request merged**
