### PR TITLE
tmap-based maps

### PR DESCRIPTION
**Pull request by jlehtoma**
Sorry for the misleading branch name. It's not `sf`-based, but `tmap`-based maps in the package vignette.

### CODE REVIEW

**Comment by jlehtoma** [comment]
Also note, that I **did not** keep the **ggplot2**-based examples. Up to maintainers which versions should be presented in the vignette.

**Comment by jlehtoma** [comment]
`tmap` needs to go to `Suggests` and be present in TravisCI

**Comment by antagomir** [comment]
tmap added to Travis and Suggests in master.

**Comment by jlehtoma** [comment]
This PR update includes 1) the latest updates from `master`, and 2) TravisCI related configs from branch `travis-tmap`. I'll delete that branch soon.

I've resolved TravisCI errors by adjusting [the config file](https://github.com/rOpenGov/eurostat/blob/sf-based-maps/.travis.yml). A bunch of system libs and R packages were needed, but now everything seems to work. **Note also that I changed the system image to Trusty (14.04) on TravisCI.** 12.04 feels a tad conservative, but feel free to disagree.

**Pull request merged**
