### PR TITLE
eurotime2date: avoid warning when time variable is a year interval

### PR DESCRIPTION
**Pull request by briatte**
Hi,

This is a tiny bugfix for `eurotime2date.R` that avoids printing a warning when the `time` variable of a dataset is a year interval of the form `2006_2008`. The code now simply skips it.

Perhaps the same kind of fix should be applied to `eurotime2num.R` too.

### CODE REVIEW

**Comment by jhuovari** [comment]
Thank you very much for contributing. Could you still clarify:
- Rationale for the change. In which eurostat table the interval format is used?
- `eurotime2num` should return a object of class `date`. as.Date("2006_2008") does give an error. What could be a solution?

**Comment by briatte** [comment]
Hi,

1. An example of a `time` variable formatted as year intervals is table `hlth_cd_ysdr1`, "Causes of death by NUTS 2 regions - standardised death rate per 100 000 inhabitants, 3 years average". Right now, `get_eurostat` with default settings will return a warning on that table, indicating that the time format is unknown. The PR simply escapes that behaviour.

2. It is unclear to me why `eurotime2num` should return a `Date`. I was under the impression that it was meant to return numeric values instead. Perhaps the function should just escape year intervals, [like it does with daily data](https://github.com/rOpenGov/eurostat/blob/master/R/eurotime2num.R#L38-L40). Generally speaking, I find padding the time variables with nonexistent date information to be a risky default behaviour.

**Comment by jhuovari** [comment]
Ok, I see the problem. Even after that, there might still be time formats that are not covered.

Sorry, I had the wrong function in the reply. `eurotime2num()` should return a numeric and `eurotime2date()` a date. Both should be made to pass an interval format, as you propose. However, they should still give a warning. But not the present warning. Maybe something like: "Time format is an interval, no time conversion was made."

To get data without warning: `get_eurostat("hlth_cd_ysdr1", time_format = "raw")`.

**Comment by briatte** [comment]
Hi @jhuovari,

The PR now follows your instructions: trying to convert year intervals with either `eurotime2date` or `eurotime2num` returns a warning and leaves the intervals intact.

**Comment by jhuovari** [comment]
Great! Looks good. And thaks also for all typo corrections.

**Pull request merged**
