### PR TITLE
Update cache management

### LINKED ISSUE #223: Potential improvement on cache dir
Hi @antagomir 

As you know, I developed [`giscoR`](https://github.com/dieghernan/giscoR) as a kind of spatial spin-off of `eurostat`.

Recently I have been working on improving the cache dir management (previously set as `options(gisco_cache_dir = "path")`, similar to the desing on `eurostat`).  Now the cache is set by storing a persistent path using [rappdirs::user_cache_dir()](https://rappdirs.r-lib.org/reference/user_cache_dir.html), that is loaded as an environment variable at the beginning of the session. 

That means that `options()` command is not needed, in fact the users don't have to worry about the cache any more, that is managed internally by the package. The cache dir can be modified persistently with a custom function (see https://dieghernan.github.io/giscoR/reference/gisco_set_cache_dir.html for Details).

Source code: See https://github.com/dieghernan/giscoR/blob/master/R/gisco_cache.R

If this is something you would like to explore for implementing it also in your package ping me and I could start to have a look on it.

Regards

### PR DESCRIPTION
**Pull request by dieghernan**
Closes #223 

See here an implementation of the new cache management. There is a suite of functions that detects the current cache dir (either set up via parameter, via `options(eurostat_cache_dir` or installed in the machine) and manages the download.

A similar suite is implemented in two of my packages, already on CRAN:  https://github.com/rOpenGov/giscoR and https://github.com/rOpenSpain/mapSpain

The current approach only writes on the temporary directory unless the user set a cache dir. Also, for storing the persistent cache dir with `rappdirs` the user needs to explicitly install the cache dir path with `install = TRUE`.

I updated also some links, the cache parts on the functions that uses it and the `clean_eurostat_cache` function.

There is also a whole test suite for that. Note that the test suite also switches temporarly the cache dir to run the tests on a temporary dir, so no files are downloaded or removed on the local machine.

By last, I updated the GH check action to cache dependencies also for Windows (would reduce significantly the running time) and for showing the tests output.

### CODE REVIEW

**Review by antagomir — APPROVED** [review]
Seems good!

**Comment by dieghernan** [comment]
Hi! I’ll tackle your comments and I would let you know, thanks both

**Comment by dieghernan** [comment]
It’s done now, moving to testthat 3 made me change some tests due to deprecations (a bit of pain).

I’ll leave it to you if finally you decided to merge @antagomir @pitkant

**Comment by antagomir** [comment]
Ok to me, how about @pitkant

**Review by pitkant — APPROVED** [review]
Thank you for your hard work, looks great!

**Pull request merged**
