### PR TITLE
Regional data products

### PR DESCRIPTION
**Pull request by antaldaniel**
- Identify mis-labelled observations
- Recode where there were no boundary changes
- Detect discontinued regions
- Give guideance on further correspondence possibilities.

They need to import two new data frames with the helper function in data-raw.

I added a short description to each file.  Unfortunately, I cannot fully run the tests in Windows locally with devtool, I do not understand why, but I think that the files are correct.

So, please, first create the  new files in the data-raw, import the data files needed for detecting issues, 
then go on with the new helper functions. 

If these work, I will add some more with a long-form documentation in an article.

### CODE REVIEW

**Comment by antagomir** [comment]
Thanks. Testing now. I get:

> library(devtools)
Loading required package: usethis
> document()
Updating eurostat documentation
Loading eurostat
Error: 'nuts_correspondence' is not an exported object from 'namespace:eurostat'

I may be able to debug this more tomorrow but it seems that the harmonize_geo_code is using nuts_correspondence but it is not defined in the function. This might be the cause.

**Comment by antagomir** [comment]
Ok, it seems that the data sets that are documented should be available in the data folder.

For instance, the data sets documented in R/data_countries.R are available in data/*.rda

Now, the data sets documented in R/data_nuts_correspondence.R is not available in data/ folder. 

This is leading to the error message listed above. If the idea is that this data is generally being made available within the package, then I would propose adding it in the data/ folder as an rda (RData) file unless there are problems / other suggestions.

**Comment by antaldaniel** [comment]
I made a new PR, and sorry for the too short commit message. The file that creates the missing data file(s) is in data-raw/nuts_coding.R - similarly to the country group data file creator.  devtools is not running this.  I now run it, and committed both the results and the files, but you may have to do it on the branch to avoid version problems.  

If you run data-raw/nuts_coding.R, it will download the Eurostat correspondence table, tidy it iup, and save it with usethis::   as a package data.  The nuts_correspondence table then will be in the package.

**Comment by antagomir** [comment]
Can we have this PR into devel?

**Pull request merged**
