### PR TITLE
Add rogtemplate to eurostat 

### LINKED ISSUE #76: Create release & Add DOI in README
When the final version is submission-ready, create release and add DOI.

### LINKED ISSUE #132: Sticker for eurostat
Create a sticker for the package. For preliminary template, see inst/extras/sticker.R

### PR DESCRIPTION
**Pull request by dieghernan**
Following https://github.com/orgs/rOpenGov/projects/2 and https://github.com/orgs/rOpenGov/teams/core/discussions/2

Close #132

Close #76

### CODE REVIEW

**Review by antagomir — APPROVED** [review]
Seems good to me! Shall we merge after the checks? Some checks seem to fail still.

**Comment by dieghernan** [comment]
I’ll wait until #228 is merged to avoid conflict. Check are failing because the action can’t download rcmdcheck on Ubuntu devel:

ubuntu-20.04 (devel)
there is no package called ‘rcmdcheck’

So this is not related with the PR, it seems to be a temporary issue (hope so, all packages are failing now for the same reason)

ping @pitkant

**Comment by dieghernan** [comment]
Closes #132

**Comment by dieghernan** [comment]
Hi @antagomir 

I also updated the README adding the DOI of R-Journal https://doi.org/10.32614/RJ-2017-019 and updated the citation to best align with the one provided there.

As this can be a sensitive change I would wait for your feedback

**Pull request merged**
