### PR TITLE
Refresh datasets

### LINKED ISSUE #245: eu_countries and eu_candidate_countries outdated
I noticed that the `eu_countries` dataset still contains UK.
From an already closed issues, #131 I understand that the `eu_countries` dataset reflects the data in [1] which doesn't list UK anymore.

The `eu_candidate_countries` is also incomplete: MD and UA are missing.

[1] https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Tutorial:Country_codes_and_protocol_order#Codes.2C_names_and_protocol_order_of_European_Union_.28EU.29_Member_States

### PR DESCRIPTION
**Pull request by espinielli**
fixes #245

### CODE REVIEW

**Review by antagomir — APPROVED** [review]
Seems good.

I am starting to wonder why we have decided to include these super simlple data frames as rda files instead of plain text CSVs that could be accessed with system.file() and browsed in online code more easily. But perhaps that would be another PR.

**Comment by antagomir** [comment]
If you see easily how to fix the GHA failure that would be great..

**Comment by espinielli** [comment]
This fails even without my changes, i.e. from a fresh clone of the repo...

**Comment by espinielli** [comment]
I checked out v3.2.1 (the most recently tagged Release version) and I get errors there too...

**Comment by espinielli** [comment]
CRAN on the other end says the version is 3.7.12...I am, a little bit confused by the Release numbering.

**Comment by antagomir** [comment]
Ok I opened an issue. 

I can approve the changes for this PR. and we have to find a fix for the builds. 

If you like you can add yourself on the DESCRIPTION file contributor list (ctb) as part of this PR before we merge.

This may take until after the Xmas break at least... But if you can meanwhile find a fix, that would be greatly appreciated!

**Comment by espinielli** [comment]
I added myself as contributor: thanks.
I also investigated the issue with the failure (missing dict on eurostat bulk download site), see the relevant details in issue #248

**Comment by antagomir** [comment]
Ok I merge this now, we must troubleshoot the other issues separately and this does not seem to affect most of the key functionality.

**Comment by antagomir** [comment]
Thanks!

**Pull request merged**
