### PR TITLE
See enhancement issue #128

### PR DESCRIPTION
**Pull request by antaldaniel**
I added more functionality compared to Przemyslaw's initial idea, however, at the expense of adding a further dependency on the rOpenSci package RefManageR.

I believe that it is a rather widely used package, and the enhancement pays of for reproducible research.

I also added three units tests, and rather extensive exception handling for parameters. 

On the other hand, there is a tiny issue remaining, the last metadata always ends in a , which comes from RefManageR and is not strictly correct.  I wonder if there is an easy way to remove it.

### CODE REVIEW

**Comment by antagomir** [comment]
Travis tests still fail and I can't see immediately from the reports why. I wonder if this might be related to .travis.yml file ie. perhaps the dependency has to be added there as well?

**Comment by antaldaniel** [comment]
I have no idea, I added the dependency in the NAMESPACE and as @importFrom, but I do not know if on Travis you need to explicitly download the dependency?

**Comment by antagomir** [comment]
Ok then I have one request. Could you make the pull request to the "devel" branch, so we can make sure that this works before pushing to master? I can check travis then.

**Comment by antagomir** [comment]
I assume this was the one that was then later PR̈́ed to devel branch and merged, so I close this.

**Pull request closed without merging**
